services:
  rag_mongo:
    image: mongo:7
    container_name: rag_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - rag_mongo_data:/data/db

  rag_redis:
    image: redis:7
    container_name: rag_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - rag_redis_data:/data

  rag_qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_qdrant
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - rag_qdrant_data:/qdrant/storage

volumes:
  rag_mongo_data:
  rag_redis_data:
  rag_qdrant_data:
